### ISSUE TITLE
[Bug]:  Ready to Reawaken implementation not working

### ISSUE THREAD

**Issue by SlanDF** [DelvUI/DelvUI#1226]
### What are you trying to do?

Use the Ready to Reawaken Color

### What is the expected behavior?

Ready to Reawaken to be enabled when Ready to Reawaken is up

### What actually happened?

Ready to Reawaken Color option is definitely not checking the correct ID (3671) and the color picker is just a copy paste of the serpent offerings bar

### FFXIV Update

- [X] I have confirmed that I have the latest version of XIVLauncher and DelvUI.

**Comment by Zeffuro** [comment]
Ah I see, I need to check for both 50 Gauge and the status, didn't realize Serpents Ire worked like that. Will make a change for that.

For the color I was torn because the bar itself is already blue and if I had changed Serpents Offering to red for example then almost every single bar is red and I didn't want to introduce a sudden new color for people who were used to the previous gauge. If you have a good color suggestion, let me know.

**Comment by SlanDF** [comment]
the color being the same by default is fine, but when you try to use that color picker it'll also change the fill color, so the Ready to Reawaken Color colorpicker is doing the same as the Fill Color colorpicker

**Comment by Zeffuro** [comment]
Implemented a fix in my Vipersight rework PR, if cultbaus doesn't find any issues with my changes then this should be merged soon.
