### ISSUE TITLE
[Suggestion]: Simple logic applied to Text Tags

### ISSUE THREAD

**Issue by Random-Stack-Random-Day** [DelvUI/DelvUI#944]
### Add a string to a text tag only if it has a value
**_Minor_** cosmetic upgrade
E.g.
`[distance>0'y']` would show `15y` on a target 15 yalms away, but something like a gardening node wouldn't show anything.
It currently shows it as this with tag of `[distance]y`:
![image](https://user-images.githubusercontent.com/13740813/147837114-7e188ea0-f158-43c0-9e26-0151f3f74b0b.png)

### Only return value if integer is matching requirements set 
_**Functional**_ cosmetic upgrade
E.g.

`[0>health-deficit]` or `[health-deficit<0]` would return nothing at 0 health, and return -100 at 100 health missing. This removes clutter for people who like to display more common information.

My use-case is exclusively for not showing '0' for health deficit but I could see uses such as only showing mana when under 25% (rez warning), or 80% (lucid warning).

**Comment by mkarer** [comment]
for reference this is how it works in ouf: https://github.com/oUF-wow/oUF/blob/master/elements/tags.lua (ouf is what we use in wow since more than a decade) - ouf tags support prefix + suffix values (and passing args to tag functions) and most tags only return values when they're not 0, that way empty tags dont display prefix + suffix and they can be used to add spacing, parentheses or whatever

i added support for prefixes and suffixes [here](https://github.com/mkarer/DelvUI/commit/bc0791abe0798f4fad9fdcf8d52a8299e1da786e), but i'm neither an expert in c# nor when it comes to regular expressions

some way to add custom tags would be nice aswell (for example on party frames "name > 90% hp and missing hp <= 90% hp", because i like minimal stuff and names are getting irrelevant when someone needs healing, but everyone has different preferences i guess) (as would be different colors, but that seems to be a pita with imgui)

**Comment by vond82** [comment]
Will look into this once I have some free time (hard to come by atm), but ofc feel free to continue working on it yourself and make a PR if you prefer :) It definitely would be a nice feature.
